In [1]:
# Diamond Price Prediction

# Import Dependencies
import pandas as pd
import numpy as np
# Import data
data = pd.read_csv(r'C:\Users\Sufiyan\Db_DataSets\diamonds.csv')
# display first 5 rows
data.head()

Unnamed: 0  carat      cut color clarity  depth  table  price     x     y  \
0           1   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98   
1           2   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84   
2           3   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07   
3           4   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23   
4           5   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35   

      z  
0  2.43  
1  2.31  
2  2.31  
3  2.63  
4  2.75

In [2]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
data['cut']= label_encoder.fit_transform(data['cut'])
data['cut'].unique()

array([2, 3, 1, 4, 0])

In [3]:
data['clarity']= label_encoder.fit_transform(data['clarity'])
data['clarity'].unique()

array([3, 2, 4, 5, 7, 6, 0, 1])

In [4]:
x = data.drop(['Unnamed: 0', 'price', 'color'], axis = 1)
y = data.drop(['Unnamed: 0', 'carat', 'color', 'cut', 'clarity', 'table', 'depth', 'x', 'y', 'z'], axis = 1)

In [5]:
x.head()

carat  cut  clarity  depth  table     x     y     z
0   0.23    2        3   61.5   55.0  3.95  3.98  2.43
1   0.21    3        2   59.8   61.0  3.89  3.84  2.31
2   0.23    1        4   56.9   65.0  4.05  4.07  2.31
3   0.29    3        5   62.4   58.0  4.20  4.23  2.63
4   0.31    1        3   63.3   58.0  4.34  4.35  2.75

In [6]:
y.head()

price
0    326
1    326
2    327
3    334
4    335

In [7]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 0)
x_train.shape

(37758, 8)

In [8]:
x_train.shape

(37758, 8)

In [9]:
y_train.shape

(37758, 1)

In [10]:
x_test.shape

(16182, 8)

In [11]:
x_test

carat  cut  clarity  depth  table     x     y     z
10176   1.10    2        3   62.0   55.0  6.61  6.65  4.11
16083   1.29    2        2   62.6   56.0  6.96  6.93  4.35
13420   1.20    3        2   61.1   58.0  6.88  6.80  4.18
20407   1.50    2        2   60.9   56.0  7.43  7.36  4.50
8909    0.90    4        5   61.7   57.0  6.17  6.21  3.82
...      ...  ...      ...    ...    ...   ...   ...   ...
49313   0.34    2        2   61.8   54.0  4.48  4.51  2.78
32991   0.38    3        5   61.7   59.0  4.64  4.60  2.85
18841   1.51    4        3   60.4   59.0  7.27  7.30  4.40
25490   2.18    2        3   62.6   55.0  8.27  8.22  5.16
17489   2.05    1        0   56.9   58.0  8.46  8.30  4.77

[16182 rows x 8 columns]

In [12]:
y_test.shape

(16182, 1)

In [13]:
y_test

price
10176   4733
16083   6424
13420   5510
20407   8770
8909    4493
...      ...
49313    540
32991    812
18841   7723
25490  14277
17489   7026

[16182 rows x 1 columns]

In [14]:
from sklearn.linear_model import LinearRegression
ml = LinearRegression()
ml.fit(x_train, y_train)

LinearRegression()

In [15]:
y_pred = ml.predict(x_test)
y_pred

array([[ 6102.10860285],
       [ 7245.02759048],
       [ 6513.48350526],
       ...,
       [ 9701.55457257],
       [15521.39607053],
       [13708.65103558]])

In [16]:
from sklearn.metrics import r2_score
score = r2_score(y_test, y_pred)
y_pred

array([[ 6102.10860285],
       [ 7245.02759048],
       [ 6513.48350526],
       ...,
       [ 9701.55457257],
       [15521.39607053],
       [13708.65103558]])

In [17]:
print(score)

0.8746567351780357


In [18]:
x_test = [[0.23 ,4 ,2 ,56.9 ,63.0 ,4.55 ,4.17 ,2.30]]
y_pred = ml.predict(x_test)
y_pred*-1

array([[940.69785827]])

In [19]:
x_test = [[0.13 ,2 ,3 ,58 ,65.0 ,4.25 ,4.17 ,2.50]]
y_pred = ml.predict(x_test)
y_pred*-1

array([[1891.92666373]])